import { pool } from "../config/postgres.js";
import fs from 'fs';
import csv from 'csv-parser';
import { env } from "../config/env.js";
import { customerSchema } from "../models/transcripts.js";

export async function queryTables() {
    const client = await pool.connect();
    
    try {
        // Iniciamos transacción - si algo falla, se revierte todo
        await client.query('BEGIN');

        // tabla supplier - Información de proveedores
        await client.query(`
            CREATE TABLE IF NOT EXISTS "supplier" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"name" VARCHAR(50) NOT NULL,
	"email" VARCHAR(50) NOT NULL UNIQUE,
	PRIMARY KEY("id")
);
        `);

     // tabla category - Información de categorías de productos
        await client.query(`
            
CREATE TABLE IF NOT EXISTS "category" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"name" VARCHAR(50) NOT NULL UNIQUE,
	PRIMARY KEY("id")
);
        `);

    // tabla city - Información de ciudades
        await client.query(`
    CREATE TABLE IF NOT EXISTS "city" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"name" VARCHAR(50) NOT NULL UNIQUE,
	PRIMARY KEY("id")
);
        `);

      // tabla product - Información de productos
        await client.query(`
            CREATE TABLE IF NOT EXISTS "product" (
	"id" VARCHAR(30) NOT NULL UNIQUE,
	"name" VARCHAR(100) NOT NULL,
	"price" INTEGER NOT NULL,
	"category_id" INTEGER NOT NULL,
	PRIMARY KEY("id")
);

        `);

        // order - pedidos realizados por los clientes
        await client.query(`
            CREATE TABLE IF NOT EXISTS "order" (
	"id" VARCHAR(30) NOT NULL UNIQUE,
	"date" DATE,
	PRIMARY KEY("id")
);
        `);
        
        // customer - Información de clientes
        await client.query(`
            CREATE TABLE IF NOT EXISTS "customer" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"name" VARCHAR(50) NOT NULL,
	"email" VARCHAR(50) NOT NULL UNIQUE,
	"address" VARCHAR(50) NOT NULL,
	"phone" VARCHAR(50) NOT NULL,
	"city_id" INTEGER NOT NULL,
	PRIMARY KEY("id")
);
        `);

    // transaction - registra los detalles de cada orden
        await client.query(`CREATE TABLE IF NOT EXISTS "transaction" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"quantity" INTEGER NOT NULL,
	"total_value" INTEGER NOT NULL,
	"product_id" VARCHAR(30) NOT NULL,
	"supplier_id" INTEGER NOT NULL,
	"order_id" VARCHAR(30) NOT NULL,
	"customer_id" INTEGER NOT NULL,
	PRIMARY KEY("id")
);`);
    

        // ALTER TABLE para agregar claves foráneas (FOREIGN KEYS)
        await client.query(`
ALTER TABLE "product"
ADD FOREIGN KEY("category_id") REFERENCES "category"("id")
ON UPDATE cascade ON DELETE cascade;
ALTER TABLE "transaction"
ADD FOREIGN KEY("customer_id") REFERENCES "customer"("id")
ON UPDATE cascade ON DELETE cascade;
ALTER TABLE "transaction"
ADD FOREIGN KEY("product_id") REFERENCES "product"("id")
ON UPDATE cascade ON DELETE cascade;
ALTER TABLE "customer"
ADD FOREIGN KEY("city_id") REFERENCES "city"("id")
ON UPDATE cascade ON DELETE cascade;
ALTER TABLE "transaction"
ADD FOREIGN KEY("supplier_id") REFERENCES "supplier"("id")
ON UPDATE cascade ON DELETE cascade;
ALTER TABLE "transaction"
ADD FOREIGN KEY("order_id") REFERENCES "order"("id")
ON UPDATE cascade ON DELETE cascade;
AlTER TABLE "transaction"
ADD CONSTRAINT "unique_product_order" UNIQUE ("product_id", "order_id");`);

        // Si todo salió bien, confirmamos los cambios
        await client.query('COMMIT');
        
    } catch (error) {
        // Si algo falló, revertimos todos los cambios
        await client.query('ROLLBACK');
        throw error;
    } finally {
        // Siempre liberamos la conexión
        client.release();
    }
}


// aquí es donde se hacen los INSERTS a las tablas, leyendo el CSV fila por fila
export async function queryData() {
    const client = await pool.connect();
    
    try {
        await client.query('BEGIN');

        const result = [];
        await new Promise((resolve, reject) => {
            fs.createReadStream(env.fileDataCsv)     // Abre el archivo
                .pipe(csv())                          // Procesa como CSV
                .on("data", (data) => result.push(data))  // Cada fila → array
                .on("end", resolve)                   // Terminó → resolve
                .on("error", reject);                 // Error → reject
        });
        
        // Contadores para las estadísticas de migración
        const counters = {
            countCustomers: 0,
            countProducts: 0,
            countCategories: 0,
            countSuppliers: 0,
            countOrders: 0,
            countTransactions: 0
        };
        
        for (const row of result) {
            
            // ------------------------------------------------------------
            // 2.1: LIMPIAR Y NORMALIZAR LOS DATOS
            // ------------------------------------------------------------
           
            // datos del cliente
            const customerName = row.customer_name
                .trim()                              // Quita espacios al inicio/final
                .replace(/\s+/g, ' ')                // Múltiples espacios → uno solo
                .split(' ')                          // Separa por espacios
                .map(w => w.charAt(0).toUpperCase() + w.slice(1).toLowerCase())  // Capitaliza
                .join(' ');                          // Une de nuevo
           
            // Email siempre en minúsculas y sin espacios
            const customerEmail = row.customer_email.trim().toLowerCase();
            const customerAdress = row.customer_address.trim();
            const customerCity = row.city.trim();
            const customerPhone = row.customer_phone.trim();

            // (\w+)$
            
            // Datos del supplier
            const supplierName = row.supplier_name.trim();
            const supplierEmail = row.supplier_email.trim().toLowerCase();
            
            // Datos de category
            const categoryName = row.product_category.trim();

            // Datos del producto
            const productSku = row.product_sku.trim().toUpperCase();
            const productName = row.product_name.trim();
            console.log(productName);
            const unitPrice = parseInt(row.unit_price);  // String → número entero

            // datos pedido 
            const quantity = parseInt(row.quantity);
            const totalLineValue = parseInt(row.total_line_value);

            // pedido tiene un id que luego va a transacción
            const orderId = row.transaction_id.trim().toUpperCase(); 
            const transactionDate = new Date(row.date); // Usamos la fecha del CSV para la transacción            

            // primero insertamos city
            const city_result = await client.query(`
                INSERT INTO "city" ("name") 
                VALUES ($1) 
                ON CONFLICT ("name")
                DO UPDATE SET name = EXCLUDED.name
                RETURNING xmax
            `, [customerCity]);

            // Obtenemos el ID de la ciudad para usarlo en el estudiante
            const cityId = await client.query(
                `SELECT id FROM city WHERE name = $1`, 
                [customerCity]
            );

            // luego insertamos el cliente con la ciudad
            const customer_result = await client.query(`
                INSERT INTO "customer" ("name", "email", "phone", "address", "city_id") 
                VALUES ($1, $2, $3, $4, $5) 
                ON CONFLICT ("email")
                DO UPDATE SET name = EXCLUDED.name, phone = EXCLUDED.phone, address = EXCLUDED.address
                RETURNING xmax
            `, [customerName, customerEmail, customerPhone, customerAdress, cityId.rows[0].id]);
            
            // insertamos supplier 
            const supplier_result = await client.query(`
                INSERT INTO "supplier" ("name", "email") 
                VALUES ($1, $2) 
                ON CONFLICT ("email")
                DO UPDATE SET name = EXCLUDED.name
                RETURNING xmax
            `, [supplierName, supplierEmail]);

          // insertar category 

            const category_result = await client.query(`
                INSERT INTO "category" ("name") 
                VALUES ($1) 
                ON CONFLICT ("name")
                DO UPDATE SET name = EXCLUDED.name
                RETURNING xmax
            `, [categoryName]);

            // Obtenemos el ID de la categoría para usarlo en el producto
            const categoryId = await client.query(
                `SELECT id FROM category WHERE name = $1`, 
                [categoryName]
            );

            // insertamos producto con su categoría
            const product_result = await client.query(`
                INSERT INTO "product" ("id", "name", "price", "category_id") 
                VALUES ($1, $2, $3, $4)
                ON CONFLICT ("id")
                DO UPDATE SET name = EXCLUDED.name, price = EXCLUDED.price, category_id = EXCLUDED.category_id
                RETURNING xmax
            `, [productSku, productName, unitPrice, categoryId.rows[0].id]);
            console.log(categoryId.rows[0].id);
            
            // obtenemos el ID del supplier 
            const supplierID = await client.query(
                `select id from supplier where email = $1
                `, [supplierEmail]
            )
            
                // insertamos el pedido
            const order_result = await client.query(`
                INSERT INTO "order" ("id", "date") 
                VALUES ($1, $2) 
                ON CONFLICT ("id")
                DO UPDATE SET date = EXCLUDED.date
                RETURNING xmax
            `, [orderId, transactionDate]);

// customer id para la transacción
            const customerID = await client.query(
                `select id from customer where email = $1
                `, [customerEmail]
            )
            // transaction insertamos la transacción con el cliente y producto relacionados
            // evitar duplicados: si el mismo pedido ya existe, actualizamos cantidad y valor total
            

            const transaction_result = await client.query(`
                INSERT INTO "transaction" (
    "quantity", "total_value", "product_id", 
    "supplier_id", "order_id", "customer_id"
) 
VALUES ($1, $2, $3, $4, $5, $6) 
ON CONFLICT ("product_id", "order_id")
DO UPDATE SET 
    quantity = EXCLUDED.quantity, 
    total_value = EXCLUDED.total_value, 
    supplier_id = EXCLUDED.supplier_id, 
    customer_id = EXCLUDED.customer_id
RETURNING xmax
            `, [quantity, totalLineValue, productSku, supplierID.rows[0].id, orderId, customerID.rows[0].id]);

           

            // mongoDB: actualizamos el historial académico del estudiante
            await customerSchema.findOneAndUpdate(
                { "customerEmail": customerEmail },  // Filtro de búsqueda
                {
                    // Solo aplica si es documento nuevo
                    $setOnInsert: {
                        "customerEmail": customerEmail,
                        "customerName": customerName,
                                  },
                    // Siempre agrega el pedido al historial
                    $push: {
                        "orderHistory": {
                            "orderId": orderId,
                            "date": transactionDate,
                            "totalValue": totalLineValue,
                            "products": [
                                {
                                    "productSku": productSku,
                                    "productName": productName,
                                    "quantity": quantity,
                                    "unitPrice": unitPrice
                                }
                            ]
                        }
                    }
                },
                { upsert: true } 
           
            );
            
            // ------------------------------------------------------------
            // 2.8: ACTUALIZAR CONTADORES
            // ------------------------------------------------------------
            // xmax = '0' significa que fue INSERT (registro nuevo)
            if (customer_result.rows[0].xmax === '0') counters.countCustomers++;
            if (supplier_result.rows[0].xmax === '0') counters.countSuppliers++;
            if (product_result.rows[0].xmax === '0') counters.countProducts++;
            if (category_result.rows[0].xmax === '0') counters.countCategories++;
            if (order_result.rows[0].xmax === '0') counters.countOrders++;
            if (transaction_result.rows[0].xmax === '0') counters.countTransactions++;
            }
        

        // Confirmamos todos los cambios
        await client.query('COMMIT');
        
        // Retornamos las estadísticas de la migración
        return counters;

    } catch (error) {
        console.log('Error en migración:', error);
        await client.query('ROLLBACK');
        throw error;
    } finally {
        client.release();
    }
}