import { pool } from "../config/postgres.js";
import fs from 'fs';
import csv from 'csv-parser';
import { env } from "../config/env.js";
import { AcademicTranscripts } from "../models/transcripts.js";

export async function queryTables() {
    const client = await pool.connect();
    
    try {
        // Iniciamos transacción - si algo falla, se revierte todo
        await client.query('BEGIN');

        // tabla supplier - Información de proveedores
        await client.query(`
            CREATE TABLE IF NOT EXISTS "supplier" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"name" VARCHAR(50) NOT NULL,
	"email" VARCHAR(50) NOT NULL UNIQUE,
	PRIMARY KEY("id")
);
        `);

     // tabla category - Información de categorías de productos
        await client.query(`
            
CREATE TABLE IF NOT EXISTS "category" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"name" VARCHAR(50) NOT NULL UNIQUE,
	PRIMARY KEY("id")
);
        `);

    // tabla city - Información de ciudades
        await client.query(`
    CREATE TABLE IF NOT EXISTS "city" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"name" VARCHAR(50) NOT NULL UNIQUE,
	PRIMARY KEY("id")
);
        `);

      // tabla product - Información de productos
        await client.query(`
            CREATE TABLE IF NOT EXISTS "product" (
	"id" VARCHAR(30) NOT NULL UNIQUE,
	"name" VARCHAR(50) NOT NULL,
	"price" INTEGER NOT NULL,
	"category_id" INTEGER NOT NULL,
	PRIMARY KEY("id")
);

        `);

        // product_supplier - Relación entre productos y proveedores (muchos a muchos)
        await client.query(`
            CREATE TABLE IF NOT EXISTS "product_supplier" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"supplier_id" INTEGER NOT NULL,
	"product_id" VARCHAR(30) NOT NULL,
	PRIMARY KEY("id")
);
        `);
        
        // customer - Información de clientes
        await client.query(`
             CREATE TABLE IF NOT EXISTS "customer" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"name" VARCHAR(50) NOT NULL,
	"email" VARCHAR(50) NOT NULL UNIQUE,
	"address" VARCHAR(50) NOT NULL,
	"phone" VARCHAR(50) NOT NULL,
	"city_id" INTEGER NOT NULL,
	PRIMARY KEY("id")
);
        `);

    // transaction - Registra cada venta realizada
        await client.query(`CREATE TABLE IF NOT EXISTS "transaction" (
	"id" VARCHAR(30) NOT NULL UNIQUE,
	"quantity" INTEGER NOT NULL,
	"date" TIME NOT NULL,
	"total_value" INTEGER NOT NULL,
	"product_id" VARCHAR(30) NOT NULL,
	"customer_id" INTEGER NOT NULL,
	PRIMARY KEY("id")
);`);
    

        // ALTER TABLE para agregar claves foráneas (FOREIGN KEYS)
        await client.query(`
ALTER TABLE "product"
ADD FOREIGN KEY("category_id") REFERENCES "category"("id")
ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE "product_supplier"
ADD FOREIGN KEY("supplier_id") REFERENCES "supplier"("id")
ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE "product_supplier"
ADD FOREIGN KEY("product_id") REFERENCES "product"("id")
ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE "transaction"
ADD FOREIGN KEY("customer_id") REFERENCES "customer"("id")
ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE "transaction"
ADD FOREIGN KEY("product_id") REFERENCES "product"("id")
ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE "customer"
ADD FOREIGN KEY("city_id") REFERENCES "city"("id")
ON UPDATE CASCADE ON DELETE CASCADE;`);

        // Si todo salió bien, confirmamos los cambios
        await client.query('COMMIT');
        
    } catch (error) {
        // Si algo falló, revertimos todos los cambios
        await client.query('ROLLBACK');
        throw error;
    } finally {
        // Siempre liberamos la conexión
        client.release();
    }
}


// aquí es donde se hacen los INSERTS a las tablas, leyendo el CSV fila por fila
export async function queryData() {
    const client = await pool.connect();
    
    try {
        await client.query('BEGIN');

        const result = [];
        await new Promise((resolve, reject) => {
            fs.createReadStream(env.fileDataCsv)     // Abre el archivo
                .pipe(csv())                          // Procesa como CSV
                .on("data", (data) => result.push(data))  // Cada fila → array
                .on("end", resolve)                   // Terminó → resolve
                .on("error", reject);                 // Error → reject
        });
        
        // Contadores para las estadísticas de migración
        const counters = {
            contStudents: 0,
            contCourses: 0,
            contEnrollments: 0,
            contProfessors: 0,
            contDepartments: 0
        };
        
        for (const row of result) {
            
            // ------------------------------------------------------------
            // 2.1: LIMPIAR Y NORMALIZAR LOS DATOS
            // ------------------------------------------------------------
           
            // datos del cliente
            const customerName = row.customer_name
                .trim()                              // Quita espacios al inicio/final
                .replace(/\s+/g, ' ')                // Múltiples espacios → uno solo
                .split(' ')                          // Separa por espacios
                .map(w => w.charAt(0).toUpperCase() + w.slice(1).toLowerCase())  // Capitaliza
                .join(' ');                          // Une de nuevo
           
            // Email siempre en minúsculas y sin espacios
            const customerEmail = row.customer_email.trim().toLowerCase();
            const customerAdress = row.customer_address.trim();
            const customerCity = row.customer_city.trim();
            const customerPhone = row.customer_phone.trim();

            // (\w+)$
            
            // Datos del supplier
            const supplierName = row.supplier_name.trim();
            const supplierEmail = row.supplier_email.trim().toLowerCase();
            
            // Datos de category
            const categoryName = row.product_category.trim();

            // Datos del producto
            const productSku = row.product_sku.trim().toUpperCase();
            const productName = row.product_name.trim();
            const unitPrice = parseInt(row.unit_price);  // String → número entero

            // datos pedido 
            const quantity = parseInt(row.quantity);
            const totalLineValue = parseInt(row.total_line_value);
            const transactionDate = new Date(); // Usamos la fecha actual para la transacción



            // primero insertamos city
            const city_result = await client.query(`
                INSERT INTO "city" ("name") 
                VALUES ($1) 
                ON CONFLICT ("name")
                DO UPDATE SET name = EXCLUDED.name
                RETURNING xmax
            `, [customerCity]);

            // Obtenemos el ID de la ciudad para usarlo en el estudiante
            const cityId = await client.query(
                `SELECT id FROM city WHERE name = $1`, 
                [customerCity]
            );

            // luego insertamos el cliente con la ciudad
            const customer_result = await client.query(`
                INSERT INTO "customer" ("name", "email", "phone", "address", "city_id") 
                VALUES ($1, $2, $3, $4, $5) 
                ON CONFLICT ("email")
                DO UPDATE SET name = EXCLUDED.name, phone = EXCLUDED.phone, address = EXCLUDED.address
                RETURNING xmax
            `, [customerName, customerEmail, customerPhone, customerAdress, cityId.rows[0].id]);
            
            // insertamos supplier 
            const supplier_result = await client.query(`
                INSERT INTO "supplier" ("name", "email") 
                VALUES ($1, $2) 
                ON CONFLICT ("email")
                DO UPDATE SET name = EXCLUDED.name
                RETURNING xmax
            `, [supplierName, supplierEmail]);

          // insertar category 

            const category_result = await client.query(`
                INSERT INTO "category" ("name") 
                VALUES ($1) 
                ON CONFLICT ("name")
                DO UPDATE SET name = EXCLUDED.name
                RETURNING xmax
            `, [categoryName]);

            // Obtenemos el ID de la categoría para usarlo en el producto
            const categoryId = await client.query(
                `SELECT id FROM category WHERE name = $1`, 
                [categoryName]
            );

            // insertamos producto con su categoría
            const product_result = await client.query(`
                INSERT INTO "product" ("id", "name", "price", "category_id") 
                VALUES ($1, $2, $3, $4) 
                ON CONFLICT ("id")
                DO UPDATE SET name = EXCLUDED.name, price = EXCLUDED.price, category_id = EXCLUDED.category_id
                RETURNING xmax
            `, [productSku, productName, unitPrice, categoryId.rows[0].id]);
            
            // obtenemos el ID del supplier 
            const supplierID = await client.query(
                `select id from supplier where email = $1
                `, [supplierEmail]
            )
            // insertamos relación producto-proveedor
            const productSupplier_result = await client.query(`
                INSERT INTO "product_supplier" ("supplier_id","product_id") 
                VALUES ($1, $2) 
                ON CONFLICT ("supplier_id", "product_id")
                DO NOTHING
                RETURNING xmax
            `, [supplierID.rows[0].id, productSku]);

            // transaction insertamos la transacción con el cliente y producto relacionados
            const transaction_result = await client.query(`
                INSERT INTO "transaction" ("id", "quantity", "date", "total_value", "product_id", "customer_id") 
                VALUES ($1, $2, $3, $4, $5, $6) 
                ON CONFLICT ("id")
                DO UPDATE SET quantity = EXCLUDED.quantity, date = EXCLUDED.date, total_value = EXCLUDED.total_value, product_id = EXCLUDED.product_id, customer_id = EXCLUDED.customer_id
                RETURNING xmax
            `, [row.transaction_id, quantity, transactionDate, totalLineValue, productSku, cityId.rows[0].id]);

            // ------------------------------------------------------------
            // 2.7: ACTUALIZAR KARDEX EN MONGODB
            // ------------------------------------------------------------
            /**
             * findOneAndUpdate con upsert:
             * - Busca un documento por studentEmail
             * - Si NO existe → lo crea ($setOnInsert)
             * - Siempre agrega el curso al historial ($push)
             * 
             * $setOnInsert: Solo se aplica si es INSERT (documento nuevo)
             * $push: Agrega un elemento al array (siempre se ejecuta)
             */
            await AcademicTranscripts.findOneAndUpdate(
                { "studentEmail": studentEmail },  // Filtro de búsqueda
                {
                    // Solo aplica si es documento nuevo
                    $setOnInsert: {
                        "studentEmail": studentEmail,
                        "studentName": studentName,
                        "summary": {
                            "totalCreditsEarned": 4,    // Valor inicial (se actualiza después)
                            "averageGrade": 4.5         // Valor inicial (se actualiza después)
                        },
                    },
                    // Siempre agrega el curso al historial
                    $push: {
                        "academicHistory": {
                            "courseCode": courseCode,
                            "courseName": courseName,
                            "credits": credits,
                            "semester": semester,
                            "professorName": professorName,
                            "grade": grade,
                            "status": "Aprobado"
                        }
                    }
                },
                { upsert: true }  // Si no existe, créalo
            );
            
            // ------------------------------------------------------------
            // 2.8: ACTUALIZAR CONTADORES
            // ------------------------------------------------------------
            // xmax = '0' significa que fue INSERT (registro nuevo)
            if (student_result.rows[0].xmax === '0') counters.contStudents++;
            if (course_result.rows[0].xmax === '0') counters.contCourses++;
            if (enrollment_result.rows[0].xmax === '0') counters.contEnrollments++;
            if (professor_result.rows[0].xmax === '0') counters.contProfessors++;
            if (department_result.rows[0].xmax === '0') counters.contDepartments++;
        }
        
        // ================================================================
        // PASO 3: ACTUALIZAR RESÚMENES EN MONGODB
        // ================================================================
        /**
         * Ahora que todos los datos están cargados, calculamos:
         * - Total de créditos por estudiante
         * - Promedio de notas por estudiante
         * 
         * Esto se hace con una consulta SQL que agrupa por estudiante.
         */
        let totalCredits = await client.query(`
            SELECT 
                ROUND(AVG(e.grade), 1) as average_grade,
                s.email,
                SUM(c.credits) as total_credits 
            FROM student s 
            JOIN enrrollments e ON s.id = e.student_id                      
            JOIN course c ON e.course_code = c.code 
            GROUP BY s.email;
        `);
        
        // Actualizamos el resumen de cada estudiante en MongoDB
        for (const student of totalCredits.rows) {
            await AcademicTranscripts.updateOne(
                { studentEmail: student.email },
                {
                    $set: {
                        "summary.totalCreditsEarned": parseInt(student.total_credits),
                        "summary.averageGrade": parseFloat(student.average_grade)
                    }
                }
            );
        }

        // Confirmamos todos los cambios
        await client.query('COMMIT');
        
        // Retornamos las estadísticas de la migración
        return counters;

    } catch (error) {
        console.log('❌ Error en migración:', error);
        await client.query('ROLLBACK');
        throw error;
    } finally {
        client.release();
    }
}

/**
 * ============================================================================
 * CONCEPTOS IMPORTANTES DE ESTE ARCHIVO:
 * ============================================================================
 * 
 * 1. ETL (Extract, Transform, Load)
 *    - Extract: Leer datos de una fuente (CSV)
 *    - Transform: Limpiar y normalizar datos
 *    - Load: Cargar en destino (PostgreSQL, MongoDB)
 * 
 * 2. IDEMPOTENCIA
 *    Una operación es idempotente si ejecutarla múltiples veces
 *    produce el mismo resultado que ejecutarla una vez.
 *    ON CONFLICT ... DO UPDATE logra esto.
 * 
 * 3. TRANSACCIONES
 *    BEGIN/COMMIT/ROLLBACK garantizan que todos los cambios
 *    se aplican juntos o ninguno se aplica.
 * 
 * 4. NORMALIZACIÓN
 *    En lugar de repetir "Ingeniería" en cada profesor,
 *    creamos una tabla department y usamos IDs.
 *    Esto ahorra espacio y evita inconsistencias.
 * 
 * 5. FOREIGN KEYS
 *    Garantizan integridad referencial:
 *    No puedes tener un curso con un profesor que no existe.
 */